% Use the CSV generated by DataExtraction
% This is easier than calling C# directly

data = readtable("in/extracted_data.csv");
data.EmotionType = categorical(data.EmotionType);

disp('Category counts:');
names = categories(data.EmotionType);
counts = countcats(data.EmotionType);
for i = 1:length(names)
    fprintf('%s: %d\n', names{i}, counts(i));
end

% Write to file for LaTeX
countsTable = table(names, counts, 'VariableNames', ["Name", "Count"]);
writetable(countsTable, 'out/category_counts.csv');

clear names counts i countsTable;
