

% Import data from CSVs
% Use the CSV generated by DataExtraction
% This is easier than calling C# directly

% //TODO: Remove datastores as they are not used

[annotations_ob, datastore_ob] = load_data("in/oblivion/extracted_data_oblivion.csv", "in/oblivion/voice/");
samplerate_ob = 44100;
write_counts_table(annotations_ob.EmotionType, "out/category_counts_oblivion.csv");

[annotations_nv, datastore_nv] = load_data("in/newvegas/extracted_data_new_vegas.csv", "in/newvegas/voice/");
samplerate_nv = 22050;
write_counts_table(annotations_nv.EmotionType, "out/category_counts_new_vegas.csv");

save('extracted_data.mat');

% Train both models
% //TODO: This, put training in a function. Save after training

