

% Import data from CSVs
% Use the CSV generated by DataExtraction
% This is easier than calling C# directly

annotations_ob = load_data("in/oblivion/extracted_data_oblivion.csv");
samplerate_ob = 44100;
write_counts_table(annotations_ob.EmotionType, "out/category_counts_oblivion.csv");

annotations_nv = load_data("in/newvegas/extracted_data_new_vegas.csv");
samplerate_nv = 22050;
write_counts_table(annotations_nv.EmotionType, "out/category_counts_new_vegas.csv");

% Remove the "Pained" category from the New Vegas data as this is not present in Oblivion
annotations_nv = annotations_nv(annotations_nv.EmotionType ~= "Pained", :);

save('extracted_data.mat');

% Train both models

[network_ob, testdata_ob, testlabels_ob] = train_single(annotations_ob, samplerate_ob, 'in/oblivion/voice/');
save('network_ob.mat', 'network_ob');
save('data_ob.mat', 'testdata_ob', 'testlabels_ob')

[network_nv, testdata_nv, testlabels_nv] = train_single(annotations_nv, samplerate_nv, 'in/newvegas/voice/');
save('network_nv.mat', 'network_nv');
save('data_nv.mat', 'testdata_nv', 'testlabels_nv')

% Benchmark both models

results_ob_ob = test_model(network_ob, testdata_ob, categories(testlabels_ob));
results_nv_nv = test_model(network_nv, testdata_nv, categories(testlabels_ob));

results_ob_nv = test_model(network_ob, testdata_nv, categories(testlabels_nv));
results_nv_ob = test_model(network_nv, testdata_ob, categories(testlabels_nv));

% Display confusion matrices and save them to files

figure;
confusionchart(testlabels_ob, results_ob_ob);
saveas(gcf, 'out/confusion_matrices_ob_ob.svg');

figure;
confusionchart(testlabels_nv, results_ob_nv);
saveas(gcf, 'out/confusion_matrices_ob_nv.svg');

figure;
confusionchart(testlabels_nv, results_nv_nv);
saveas(gcf, 'out/confusion_matrices_nv_nv.svg');

figure;
confusionchart(testlabels_ob, results_nv_ob);
saveas(gcf, 'out/confusion_matrices_nv_ob.svg');
